name: Send Tweet

       # Controls when the workflow will run
on:
  # Triggers the workflow every hour
  schedule:
    - cron: "0 * * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11.1' # install the python version needed
          
        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
        - name: execute py script # run main.py
          env:
              consumer_key: ${{ secret.CONSUMER_KEY }}
              consumer_secret: ${{ secret.CONSUMER_SECRET }}
              access_token: ${{ secret.ACCESS_TOKEN }}
              access_token_secret: ${{ secret.ACCESS_TOKEN_SECRET }}
          run: python tweet.py
