name: Send Tweet

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  # Triggers the workflow every hour
  schedule:
  # Schedule back to normal
    - cron: "0 * * * *"
    
jobs:
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11.1' # install the python version needed
          
        - name: install python packages & webdriver
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          
        - name: install chromium
          run: sudo snap install chromium
            
        - name: execute py script # run tweet.py
          env:
              CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
              CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
              ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
              BEAERER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          run: python tweet.py
              
              
